### ISSUE TITLE
生成的接口方法的路径分隔符应该是'/'现在0.0.21版本为'\'

### ISSUE THREAD

**Issue by ccfish86** [zt8989/sisyphus-cli#7]
![image](https://user-images.githubusercontent.com/15622514/99644457-ee7cb080-2a88-11eb-94cc-3b2ea27eecc6.png)

生成的接口方法的路径分隔符应该是'/'现在0.0.21版本为'\'

```
/**
 * 登录
 * POST \api\user\home\login
 * @param {UserLoginParam} bodyParams - loginParam
 */
export function login(bodyParams: UserLoginParam): Promise<UserLoginDto> {
    return request({
    url: bindUrl('\api\user\home\login', {}),
    method: 'POST',
    data: bodyParams,
    })
}

```

**Comment by zt8989** [comment]
我这边没有替换斜杠，你看下swagger返回的json

**Comment by ccfish86** [comment]
返回是正常的
问题出在`${path_1.join(data.basePath, url)}`
path_1
![image](https://user-images.githubusercontent.com/15622514/99741605-8cfe2580-2b0c-11eb-95dc-671f920174ef.png)

**Comment by ccfish86** [comment]
刚才试了下，把`path.join()`改为`path.posix.join()`可以

**Comment by zt8989** [comment]
已经修复到新版本，查看readme，现在新增了很多功能

**Comment by ccfish86** [comment]
谢谢，现在还没发现别的问题
